function skWiki(){var P='',xb='" for "gwt:onLoadErrorFn"',vb='" for "gwt:onPropertyErrorFn"',ib='"><\/script>',Z='#',Db='&',kc='../dnd.css',jc='../upload.css',cc='.cache.html',_='/',lb='//',bc=':',$b=':1',_b=':2',pb='::',Gc='<script defer="defer">skWiki.onInjectionDone(\'skWiki\')<\/script>',hb='<script id="',oc='<script language="javascript" src="',sb='=',$='?',Zb='A8705C494647103EC2E4B7338248833F',ub='Bad handler "',mc='DOMContentLoaded',ac='E6CCCEEBCD9574A5490C9558DEE94DAB',jb='SCRIPT',gb='__gwt_marker_skWiki',Jb='android',kb='base',cb='baseUrl',T='begin',S='bootstrap',bb='clear.cache.gif',rb='content',lc='css/style.css',Kb='desktop',Y='end',Cb='formfactor',Tb='gecko',Ub='gecko1_8',U='gwt.codesvr=',V='gwt.hosted=',W='gwt.hybrid',dc='gwt/clean/clean.css',wb='gwt:onLoadErrorFn',tb='gwt:onPropertyErrorFn',qb='gwt:property',ic='head',Xb='hosted.html?skWiki',hc='href',Sb='ie6',Rb='ie8',Qb='ie9',yb='iframe',ab='img',Hb='ipad',Eb='iphone',Fb='ipod',zb="javascript:''",ec='link',Wb='loadExternalRefs',mb='meta',Gb='mobile',Bb='moduleRequested',X='moduleStartup',Pb='msie',nb='name',Mb='opera',Ab='position:absolute;width:0;height:0;border:none',fc='rel',Ob='safari',Ac='sc/modules/ISC_Calendar.js',Bc='sc/modules/ISC_Calendar.js"><\/script>',sc='sc/modules/ISC_Containers.js',tc='sc/modules/ISC_Containers.js"><\/script>',nc='sc/modules/ISC_Core.js',pc='sc/modules/ISC_Core.js"><\/script>',Cc='sc/modules/ISC_DataBinding.js',Dc='sc/modules/ISC_DataBinding.js"><\/script>',wc='sc/modules/ISC_Forms.js',xc='sc/modules/ISC_Forms.js"><\/script>',qc='sc/modules/ISC_Foundation.js',rc='sc/modules/ISC_Foundation.js"><\/script>',uc='sc/modules/ISC_Grids.js',vc='sc/modules/ISC_Grids.js"><\/script>',yc='sc/modules/ISC_RichTextEditor.js',zc='sc/modules/ISC_RichTextEditor.js"><\/script>',Ec='sc/skins/Enterprise/load_skin.js',Fc='sc/skins/Enterprise/load_skin.js"><\/script>',db='script',Yb='selectingPermutation',Q='skWiki',eb='skWiki.nocache.js',ob='skWiki::',R='startup',gc='stylesheet',Ib='tablet',fb='undefined',Vb='unknown',Lb='user.agent',Nb='webkit';var m=window,n=document,o=m.__gwtStatsEvent?function(a){return m.__gwtStatsEvent(a)}:null,p=m.__gwtStatsSessionId?m.__gwtStatsSessionId:null,q,r,s,t=P,u={},v=[],w=[],x=[],y=0,z,A;o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:T});if(!m.__gwt_stylesLoaded){m.__gwt_stylesLoaded={}}if(!m.__gwt_scriptsLoaded){m.__gwt_scriptsLoaded={}}function B(){var b=false;try{var c=m.location.search;return (c.indexOf(U)!=-1||(c.indexOf(V)!=-1||m.external&&m.external.gwtOnLoad))&&c.indexOf(W)==-1}catch(a){}B=function(){return b};return b}
function C(){if(q&&r){var b=n.getElementById(Q);var c=b.contentWindow;if(B()){c.__gwt_getProperty=function(a){return H(a)}}skWiki=null;c.gwtOnLoad(z,Q,t,y);o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:X,millis:(new Date).getTime(),type:Y})}}
function D(){function e(a){var b=a.lastIndexOf(Z);if(b==-1){b=a.length}var c=a.indexOf($);if(c==-1){c=a.length}var d=a.lastIndexOf(_,Math.min(c,b));return d>=0?a.substring(0,d+1):P}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=n.createElement(ab);b.src=a+bb;a=e(b.src)}return a}
function g(){var a=F(cb);if(a!=null){return a}return P}
function h(){var a=n.getElementsByTagName(db);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(eb)!=-1){return e(a[b].src)}}return P}
function i(){var a;if(typeof isBodyLoaded==fb||!isBodyLoaded()){var b=gb;var c;n.write(hb+b+ib);c=n.getElementById(b);a=c&&c.previousSibling;while(a&&a.tagName!=jb){a=a.previousSibling}if(c){c.parentNode.removeChild(c)}if(a&&a.src){return e(a.src)}}return P}
function j(){var a=n.getElementsByTagName(kb);if(a.length>0){return a[a.length-1].href}return P}
function k(){var a=n.location;return a.href==a.protocol+lb+a.host+a.pathname+a.search+a.hash}
var l=g();if(l==P){l=h()}if(l==P){l=i()}if(l==P){l=j()}if(l==P&&k()){l=e(n.location.href)}l=f(l);t=l;return l}
function E(){var b=document.getElementsByTagName(mb);for(var c=0,d=b.length;c<d;++c){var e=b[c],f=e.getAttribute(nb),g;if(f){f=f.replace(ob,P);if(f.indexOf(pb)>=0){continue}if(f==qb){g=e.getAttribute(rb);if(g){var h,i=g.indexOf(sb);if(i>=0){f=g.substring(0,i);h=g.substring(i+1)}else{f=g;h=P}u[f]=h}}else if(f==tb){g=e.getAttribute(rb);if(g){try{A=eval(g)}catch(a){alert(ub+g+vb)}}}else if(f==wb){g=e.getAttribute(rb);if(g){try{z=eval(g)}catch(a){alert(ub+g+xb)}}}}}}
function F(a){var b=u[a];return b==null?null:b}
function G(a,b){var c=x;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
function H(a){var b=w[a](),c=v[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(A){A(a,d,b)}throw null}
var I;function J(){if(!I){I=true;var a=n.createElement(yb);a.src=zb;a.id=Q;a.style.cssText=Ab;a.tabIndex=-1;n.body.appendChild(a);o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:X,millis:(new Date).getTime(),type:Bb});a.contentWindow.location.replace(t+L)}}
w[Cb]=function(){var a=location.search;var b=a.indexOf(Cb);if(b>=0){var c=a.substring(b);var d=c.indexOf(sb)+1;var e=c.indexOf(Db);if(e==-1){e=c.length}return c.substring(d,e)}var f=navigator.userAgent.toLowerCase();if(f.indexOf(Eb)!=-1||f.indexOf(Fb)!=-1){return Gb}else if(f.indexOf(Hb)!=-1){return Ib}else if(f.indexOf(Jb)!=-1||f.indexOf(Gb)!=-1){var g=160;var h=m.screen.width/g;var i=m.screen.height/g;var j=Math.sqrt(h*h+i*i);return j<6?Gb:Ib}return Kb};v[Cb]={desktop:0,mobile:1,tablet:2};w[Lb]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return b.indexOf(Mb)!=-1}())return Mb;if(function(){return b.indexOf(Nb)!=-1}())return Ob;if(function(){return b.indexOf(Pb)!=-1&&n.documentMode>=9}())return Qb;if(function(){return b.indexOf(Pb)!=-1&&n.documentMode>=8}())return Rb;if(function(){var a=/msie ([0-9]+)\.([0-9]+)/.exec(b);if(a&&a.length==3)return c(a)>=6000}())return Sb;if(function(){return b.indexOf(Tb)!=-1}())return Ub;return Vb};v[Lb]={gecko1_8:0,ie6:1,ie8:2,ie9:3,opera:4,safari:5};skWiki.onScriptLoad=function(){if(I){r=true;C()}};skWiki.onInjectionDone=function(){q=true;o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:Wb,millis:(new Date).getTime(),type:Y});C()};E();D();var K;var L;if(B()){if(m.external&&(m.external.initModule&&m.external.initModule(Q))){m.location.reload();return}L=Xb;K=P}o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:Yb});if(!B()){try{G([Kb,Ob],Zb);G([Gb,Ob],Zb);G([Ib,Ob],Zb);G([Kb,Ob],Zb+$b);G([Gb,Ob],Zb+$b);G([Ib,Ob],Zb+$b);G([Kb,Ob],Zb+_b);G([Gb,Ob],Zb+_b);G([Ib,Ob],Zb+_b);G([Kb,Ub],ac);G([Gb,Ub],ac);G([Ib,Ub],ac);G([Kb,Ub],ac+$b);G([Gb,Ub],ac+$b);G([Ib,Ub],ac+$b);G([Kb,Ub],ac+_b);G([Gb,Ub],ac+_b);G([Ib,Ub],ac+_b);K=x[H(Cb)][H(Lb)];var M=K.indexOf(bc);if(M!=-1){y=Number(K.substring(M+1));K=K.substring(0,M)}L=K+cc}catch(a){return}}var N;function O(){if(!s){s=true;if(!__gwt_stylesLoaded[dc]){var a=n.createElement(ec);__gwt_stylesLoaded[dc]=a;a.setAttribute(fc,gc);a.setAttribute(hc,t+dc);n.getElementsByTagName(ic)[0].appendChild(a)}if(!__gwt_stylesLoaded[jc]){var a=n.createElement(ec);__gwt_stylesLoaded[jc]=a;a.setAttribute(fc,gc);a.setAttribute(hc,t+jc);n.getElementsByTagName(ic)[0].appendChild(a)}if(!__gwt_stylesLoaded[kc]){var a=n.createElement(ec);__gwt_stylesLoaded[kc]=a;a.setAttribute(fc,gc);a.setAttribute(hc,t+kc);n.getElementsByTagName(ic)[0].appendChild(a)}if(!__gwt_stylesLoaded[lc]){var a=n.createElement(ec);__gwt_stylesLoaded[lc]=a;a.setAttribute(fc,gc);a.setAttribute(hc,t+lc);n.getElementsByTagName(ic)[0].appendChild(a)}C();if(n.removeEventListener){n.removeEventListener(mc,O,false)}if(N){clearInterval(N)}}}
if(n.addEventListener){n.addEventListener(mc,function(){J();O()},false)}var N=setInterval(function(){if(/loaded|complete/.test(n.readyState)){J();O()}},50);o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:Y});o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:Wb,millis:(new Date).getTime(),type:T});if(!__gwt_scriptsLoaded[nc]){__gwt_scriptsLoaded[nc]=true;document.write(oc+t+pc)}if(!__gwt_scriptsLoaded[qc]){__gwt_scriptsLoaded[qc]=true;document.write(oc+t+rc)}if(!__gwt_scriptsLoaded[sc]){__gwt_scriptsLoaded[sc]=true;document.write(oc+t+tc)}if(!__gwt_scriptsLoaded[uc]){__gwt_scriptsLoaded[uc]=true;document.write(oc+t+vc)}if(!__gwt_scriptsLoaded[wc]){__gwt_scriptsLoaded[wc]=true;document.write(oc+t+xc)}if(!__gwt_scriptsLoaded[yc]){__gwt_scriptsLoaded[yc]=true;document.write(oc+t+zc)}if(!__gwt_scriptsLoaded[Ac]){__gwt_scriptsLoaded[Ac]=true;document.write(oc+t+Bc)}if(!__gwt_scriptsLoaded[Cc]){__gwt_scriptsLoaded[Cc]=true;document.write(oc+t+Dc)}if(!__gwt_scriptsLoaded[Ec]){__gwt_scriptsLoaded[Ec]=true;document.write(oc+t+Fc)}n.write(Gc)}
skWiki();